---
title: "Версия 30. Июнь, 2021"
weight: -10
draft: false
date:
lastmod: # search related keywords
keywords: what's new, new, новости, новое, нового, 30, июнь
---

:toc:
:toclevels: 6
:fileModTime:
:experimental:

=== Шаблоны
==== Публикация
Мы исправили работу кнопки "Опубликовать" в шаблоне. Теперь после публикации шаблона она сразу становится неактивной.

Теперь пакет будет сразу опубликован, если вы:
* скопируете его с опубликованного пакета;
* создадите пакет на основе опубликованных шаблонов, даже если он содержит несколько неопубликованных.

==== Условия
Теперь, если вы удалите часть абзаца с добавленным условием, само условие не удаляется.
Но если на весь текст под условием вы добавите разрыв страницы, условие будет удалено.

Теперь условие удаляется из группы условий на боковой панели, если отменить действие с его созданием (Redo).

Теперь при выделении любого контента в шаблоне на боковой панели отображенается кнопка "Показать условие".

==== Поля ввода
Теперь, если в колонтитулах  вы удалите ячеку таблицы и поле в ней, поле будет удалено из  списка на боковой панели.

Мы исправили работу календаря при заполнении поля типа "Дата" для 2020-2021 гг.

Мы исправили работу поля "Выбор ответа".

Теперь редактор поля в Internet Explorer открывается по первому нажатию в поле.

Мы доработали отображение названия поля в списке полей в Internet Explorer. Если название длинное, оно переносится на несколько строк.

[API] Мы исправили ошибку передачи данных методами Put и Post в запросе с заполненным параметром Value для поля Formula.

==== Блоки
Мы исправили ошибку открытия меню блока после выделения его контента в Internet Explorer.

==== Редактор текста
Функции "Отмена" и "Повтор" с текстом шаблона теперь работают правильно в Internet Explorer.

Мы исправили проблему с установкой курсора в строке таблицы.

Мы исправили ошибку, которая возникала при вставке текста, настройки отступов и последующей отмены действия.

Мы доработали применение шрифта абзаца к маркерам списка.

Мы исправили выделение контента шаблона при помощи Ctrl+A.

Теперь в браузре Internet Explorer не отображаются серые рамки вокруг контента.

==== Правило наименования документов

В Internet Explorer теперь не отображается список тегов для настройки "Правило наименования документов" при открытии или создании шаблона.

Мы доработали поиск по тегам в настройке "Правило наименования документов".

Мы исправили ошибку ввода в поле "Правило наименования документов" в браузере Safari.

=== Документы

Теперь, если вы попробуете скачать пакет с незаполненными обязательными полями, то увидите сообщение об ошибке.

Мы исправили отображение числа 0.00 при округлении отрицательного числа.

Мы доработали плагин для MS World. На месте незаполненного поля ввода в таблице в скачанном документе отображается пустая ячейка.

Мы доработали отображение таблицы при заполнении в браузере Mozilla FireFox.

Теперь ячейки вложенных таблиц подстраиваются под размеры изображений в браузере Internet Explorer.

Теперь перемещение клавишами "Вниз" и "Вверх" по списку с пустыми пунктами происходит корректно.

=== Сценарии

Мы исправили ошибку передачи названий полей через переменную в сценарии. Теперь переменная передается с постфиксом.
